### ISSUE TITLE
LzmaWriter.write should not return zero unless there's an error

### ISSUE THREAD

**Issue by jpap** [fpgaminer/rust-lzma#13] opened 2017-06-07 07:55 UTC
I've noticed that the LzmaWriter `write` can return zero bytes consumed, but then if called again and again, it will eventually accept more bytes.

This means we cannot use `write_all`, [since it will stop with error](https://github.com/rust-lang/rust/blob/master/src/libstd/io/mod.rs#L967) `ErrorKind::WriteZero` as soon as the `write` above returns zero.

The workaround is ugly,
```
let todo = buffer.len();
let mut index = 0;
while {
    let bytes = decompressor.write(&buffer[index..]).unwrap();
    index += bytes;

    index < todo
} {}
```
when it could have been just:
```
decompressor.write_all(&buffer).unwrap();
```

**Comment by fpgaminer** [comment] 2017-06-09 02:16
Thank you for reporting this bug!

Do you happen to have a sample of compressed data that causes this behavior?  I'd like to throw it into a unit test.

**Comment by fkjogu** [comment] 2017-08-16 09:23
I can also reproduce this for `LzmaWriter::new_compressor`. This is a really annoying, critical bug. I tried to isolate the failing data written into, but this does not produces the same error anymore.

Since I'm not calling `write_all` by myself, I cannot use the workaround.

**Comment by fkjogu** [comment] 2017-08-16 10:55
I think the issue is with returning `bytes_read` from `.write()` in https://github.com/fpgaminer/rust-lzma/blob/d2aac5d4643440476eaef1f9f80fbf95dc8cb6b6/src/writer.rs#L112

Since it is possible that `liblzma` has read all of the input buffer (i.e. `bytes_read == 0`), but it still needs to write data (`stream.avail_out != 0`). I think I understand why you did this, since `bytes_written` is not a good measure how many bytes where consumed from the input value, since it can be obviously of different size.
But returning `bytes_read` just does not fulfil the requirement of the `write` method in `std`.

**Comment by fkjogu** [comment] 2017-08-16 11:41
To me, encoding an error in the number of bytes written as `write_all` in `std` does is wrong. It fails, if a writer still needs to write data but does not want to consume more at a step, as in this case.

**Comment by fkjogu** [comment] 2017-08-17 11:24
This should be fixed in https://github.com/fpgaminer/rust-lzma/pull/17

**Closed** 2018-07-27 05:37 UTC
